---
- hosts: all
  vars:
    main_username: yann
  tasks:
    - name: Install base packages
      pacman:
        name: 'autoconf,automake,binutils,bison,fakeroot,file,
	      findutils,flex,gawk,gcc,gettext,grep,groff,gzip,jshon,
	      keychain,libtool,m4,make,openssh,patch,pkg-config,
              sed,sudo,texinfo,unzip,util-linux,wget,which'
        state: present
    - name: Install user apps
      pacman:
        name: 'elixir,fail2ban,neovim,rsync,python-pip,zsh'
        state: present
    - name: Set specific /etc files
      synchronize:
        mode: push
        src: files/etc/
        dest: /etc
    - name: Generate locales
      shell: locale-gen
    
    # Services
    
    - name: sshd daemon
      service: name=sshd state=started enabled=yes
    
    # User stuff
    # Groups uucp and lock are for accessing arduino & co.
    - name: Create a normal user
      user:
        name: "{{ main_username }}" 
        shell: /bin/zsh
        groups: wheel
    - name: Create a nologin user
      user:
        name: www
        shell: /sbin/nologin
    - include: dotfiles.yml
    - name: install python for neovim
      pip:
        name: neovim
        executable: /usr/bin/pip3
#
#
#
  handlers:
    - name: manage sshd service
      service: name=sshd enabled=yes state=restarted
...
